### ISSUE TITLE
License hinders use in Android applications

### ISSUE THREAD

**Issue by j-maas** [peterLaurence/MapView#10]
As far as I understand, the GNU GPLv3 license requires derivate work (e.g., an Android app using this library) to publish its source code under the same license.

Unfortunately, this is quite troublesome, not only because of politics around app development, but also because it is hard to strictly comply when publishing an Android app, as stated in the [Android Open Source Project's license explanation](https://source.android.com/setup/start/licenses), because the source code is not published along with the app.

The Android Open Source Project proposes to publish libraries under the Apache 2.0 license. As far as I can tell that license is served by including a notice about the library's license in an about page.

If this license is a conscious decision on your part, that's ok! I just wanted to point this out, because I've just come across and started to learn about this issue.

**Comment by p-lr** [comment]
You're right. I've changed the license to Apache 2.0

**Comment by j-maas** [comment]
Wow. I'm going through a rollercoaster right now. I've just read about moagrius passing away and now you've reacted to a roadblock in less than an hour.

So thank you very much for your incredible reaction and I wish you all the best going forward!
