### ISSUE TITLE
Set initial scale

### ISSUE THREAD

**Issue by dbof10** [peterLaurence/MapView#12]
Hi, thanks for the library.
I'm new to this lib. I have some questions
1. I want set the map with some initial scale value when it first renders
2. In addition, I want to run some ValueAnimator to change scale value.
3. Look at MapMarkersFragment, a callout is added every time marker is clicked. Does the lib remove the callout when tap outside?

**Comment by p-lr** [comment]
Hi, 

1. You can use `setStartScale` method on `MapViewConfiguration` builder. For example:

```kotlin
val config = MapViewConfiguration(5, 8192, 8192, tileSize, 
tileStreamProvider).setStartScale(1.5f)
```
2. You can either use `MapView.smoothScaleTo(destScale)` or use your own animator and change the scale by setting a new value for the `scale` property of the MapView at each animation step.

3. Yes the lib removes the callout when taping outside

**Comment by dbof10** [comment]
Thank you

**Comment by dbof10** [comment]
Actually there is one more question, after startScaleValue how to move it to specific region like camera api from google map?

**Comment by p-lr** [comment]
There's also the `slideToAndCenterWithScale(x, y, scale)` api.
