### ISSUE TITLE
Displaying multiple maps

### ISSUE THREAD

**Issue by c0dd3vi11** [peterLaurence/MapView#14]
Hello, @peterLaurence! Could you help me how to manage maps switching with your MapView? `redrawTiles` seems to work not correct.

I tried to make three different MapView's. But then I got a problem that sometimes tiles don't draw when I change `visibility` from `View.INVISIBLE` to `View.VISIBLE` for a next MapView.

**Comment by p-lr** [comment]
Hi,

The recommended way to switch maps is to destroy the existing `MapView` using `MapView.destroy()`, remove it from the view hierarchy, and then create a new `MapView` and configure it.
This is how it it's intended to be used.

**Comment by c0dd3vi11** [comment]
Thank you for replying. I got it.
