### ISSUE TITLE
Zoom-in/out with animation too fast

### ISSUE THREAD

**Issue by p-lr** [peterLaurence/MapView#16]
Quoting @c0dd3vi11 :
`I found this: mapView.smoothScaleFromCenter(mapView.scale * 1.5f). And the opposite is mapView.smoothScaleFromCenter(mapView.scale / 1.5f). But when I call the functions too fast then MapView starts blinking.`

**Comment by p-lr** [comment]
I'll try to reproduce this one.

**Comment by c0dd3vi11** [comment]
Sorry, that was because of my mistake: https://github.com/peterLaurence/MapView/issues/15#issuecomment-636654911

**Comment by p-lr** [comment]
No worries, and indeed, I can't reproduce this issue.
