### ISSUE TITLE
Setting initial angle and center

### ISSUE THREAD

**Issue by c0dd3vi11** [peterLaurence/MapView#18]
@peterLaurence, could you help me again, please?

I got that I can use `MapViewConfiguration.setStartScale` to initiate the scale. But how to initiate angle and center for map properly?

p.s. I'm storing angle, scale & center between launching and also want a feature to open map positioned properly on the certain map's zone.

**Comment by p-lr** [comment]
After the `MapView` has been laid out, you can do like so:

```kotlin
with(mapView) {
    angle = 15f
    val centerX = scrollX + halfWidth
    val centerY = scrollY + halfHeight
    post {
        scrollToAndCenter(centerX, centerY)
    }
}
```

**Comment by c0dd3vi11** [comment]
I'm trying to apply ReferentialData:
```
with(mapView) {
    post {
        scale = data.scale
        setAngle(data.angle)
        scrollToAndCenter(data.centerX.toInt(), data.centerY.toInt())
    }
}
```

It rotates, scales, but not scrolls...

**Comment by c0dd3vi11** [comment]
And it seems that it also moves to the top-left corner

**Comment by p-lr** [comment]
I would check the values you have for `data.centerX` and `data.centerY`.
Typically, if those values are too small, it scrolls to the top left corner.

**Comment by c0dd3vi11** [comment]
I found out that in:
```
override fun scrollTo(x: Int, y: Int) {
    val (constrainedX, constrainedY) = gestureController.setConstrainedScroll(x, y)
    super.scrollTo(constrainedX, constrainedY)
}
```
I got zeros in constrainedX, constrainedY.

**Comment by p-lr** [comment]
Can you also explain when you're trying to restore the state of MapView? Is it on device rotation (and activity re-create?)

**Comment by c0dd3vi11** [comment]
Ah, yes, the are small. Less than 1. It seems that they are between 0 an 1

**Comment by c0dd3vi11** [comment]
I'm trying to restore ReferentialData just after `configure`.

**Comment by c0dd3vi11** [comment]
I'm just trying to save it and restore to open map on a previous location.

**Comment by p-lr** [comment]
Do you know that the MapView has an automatic feature of state restore (angle, scale and scroll) on device rotation?

**Comment by c0dd3vi11** [comment]
I'm trying to share the ReferentialData between three MapView's to save the cache. To able fast switching between maps without reloading.

**Comment by c0dd3vi11** [comment]
<img width="547" alt="Screenshot 2020-06-01 at 17 09 35" src="https://user-images.githubusercontent.com/60510579/83417528-e3768b00-a42a-11ea-908b-31b0dc6d4bd5.png">

**Comment by p-lr** [comment]
If you look at the doc of `ReferentialData`:

![ref-data](https://user-images.githubusercontent.com/15638794/83417950-1288fe80-a423-11ea-88fc-580922821df3.png)

You can see that those values you have are in percent of the full width/height of your map.

**Comment by c0dd3vi11** [comment]
Oh... ^_^ That's my fault...

**Comment by c0dd3vi11** [comment]
I can't understand how to calculate real center with that percentage. Could you help me please?

**Comment by c0dd3vi11** [comment]
Should I also ally scale to the formula?

**Comment by c0dd3vi11** [comment]
<img width="506" alt="Screenshot 2020-06-01 at 18 12 54" src="https://user-images.githubusercontent.com/60510579/83423365-87643480-a433-11ea-9458-ff8d6ed6d117.png">
That works incorrect...

**Comment by p-lr** [comment]
You shouldn't use width and height, which might be 0 at the time you call
your function.
Instead, use the fullWidth and fullHeight you set at the configuration of
the MapView.

**Comment by c0dd3vi11** [comment]
Oh... this is so unobvious. I tried fullWidth/fullHeight and got the opposite situation, when viewport sticks to the right-bottom.

**Comment by c0dd3vi11** [comment]
I did the combo! ^_^
```
fun MapView.applyReferentialData(config: MapViewConfiguration, data: ReferentialData) {
    post {
        scale = data.scale
        setAngle(data.angle)
        val centerX = config.fullWidth * data.scale * data.centerX
        val centerY = config.fullHeight * data.scale * data.centerY
        scrollToAndCenter(centerX.toInt(), centerY.toInt())
    }
}
```
