### ISSUE TITLE
Redraw map tiles

### ISSUE THREAD

**Issue by lutretyakova** [peterLaurence/MapView#22]
Hi, is there a way to force refresh the map tiles. For example, when the user changes some point on the tile, I need to redraw it. Recreating the MapView doesn't work for me as there is a lot of logic there. Maybe there is a way to reload the file or canvas or something like that? Thank you

**Comment by p-lr** [comment]
Hi, I understand the use case. I'll work on that soon.

Le mer. 3 févr. 2021 à 07:48, lutretyakova <notifications@github.com> a
écrit :

**Comment by lutretyakova** [comment]
Thank you. It's great lib

**Comment by p-lr** [comment]
@lutretyakova The new `2.1.6` version has a `redrawTiles()` method on `MapView` that should work as you expect.
