### ISSUE TITLE
Marker size when changing the zoom level

### ISSUE THREAD

**Issue by sana-20** [peterLaurence/MapView#25]
Hi Peter.

I’ve been developing metro app using your library and I added multiple markers in the map.
But I come across the problem that some markers are overlapped as you can see below images.

What I want is changing the size of a marker along with the zoom level of the map or replace the marker image with other size. Say, if the map is zoomed out, the marker would be getting smaller so a user can click each marker precisely.

It would be great if you have any advice for solving this problem.

![zoom_in](https://user-images.githubusercontent.com/66289794/119620397-e76f9a00-be3f-11eb-8499-f0c0ce70ac8d.jpg)![zoom_out](https://user-images.githubusercontent.com/66289794/119620406-e9d1f400-be3f-11eb-8ccd-29f7e1274a34.jpg)

**Comment by p-lr** [comment]
Hi @sana-20 

Assuming your marker is a custom view, you need to scale it in your `onDraw()` overload.
Here is [an example](https://github.com/peterLaurence/TrekMe/blob/master/app/src/main/java/com/peterlaurence/trekme/ui/mapview/components/LineView.java), which draws a line between two points on the map. The line needs to be redrawn when the scale changes, just like your custom markers. You can see that all informations needed (scale, scroll, rotation) is taken from a `ReferentialData` instance.

To get the updated `ReferentialData` when e.g the scale changes, you need to use the `addReferentialLister` API on your MapView (see below the documentation of this API):

```kotlin
/**
 * Add a [ReferentialListener] to the MapView. This [ReferentialListener] will be notified of any
 * change of scale, rotation angle, or rotation pivot point.
 * Using this API, the MapView holds a reference on the provided [ReferentialListener] instance.
 * Don't forget to remove it when it's no longer needed, using [removeReferentialOwner].
 */
 fun addReferentialListener(listener: ReferentialListener) {
    listener.onReferentialChanged(referentialData)
    refListenerList.add(listener)
 }
```

**Comment by sana-20** [comment]
Hi @peterLaurence. Thanks for your help, it works as intended.
But `onDraw()` method is not called unlike your explanation.
I changed my custom marker class and added `addReferentialListener` in mapView, then I called `resizeMarker()` in `onReferentialChanged`.
I wonder why `onDraw()` method is not called and whether this code would cause some problem.
Please let me know if any.


```kotlin
class MapMarker @JvmOverloads constructor(context: Context, refData: ReferentialData)
   : AppCompatImageView(context), ReferentialListener {

   private var mReferentialData: ReferentialData

   init{
       mReferentialData = refData
   }

   override fun onDraw(canvas: Canvas) {
       val scale = mReferentialData.scale
       canvas.scale(scale, scale)
       super.onDraw(canvas)
   }

   override fun onReferentialChanged(refData: ReferentialData) {
       mReferentialData = refData
       resizeMarker()
       invalidate()
   }

   private fun resizeMarker() {
       val layoutParams = this.layoutParams
       layoutParams.width = (128 * mReferentialData.scale).toInt()
       layoutParams.height = (128 * mReferentialData.scale).toInt()
       this.layoutParams = layoutParams
   }
}

```

```kotlin
fun MapView.addMarker(referentialData: ReferentialData): MapMarker {
   val marker = MapMarker(context, referentialData).apply {
       setImageResource(R.drawable.img_map_marker)
   }
   addMarker(marker, 0.5, 0.5)
   addReferentialListener(marker)
   return marker
}
```

**Comment by sana-20** [comment]
Hi @peterLaurence. As your explanation, I changed my custom marker class and added `addReferentialListener` in mapView, then I called `resizeMarker()` in `onReferentialChanged`.
It works as intended now. Thanks for your help.

**Comment by p-lr** [comment]
Great!
One day, when you decide to migrate to Jetpack Compose, there will be a MapCompose library ready: https://github.com/peterLaurence/MapCompose
For now, it's too early (Jetpack Compose is in beta).
