### ISSUE TITLE
Draw polygon

### ISSUE THREAD

**Issue by shunplus** [peterLaurence/MapView#31]
I want to draw a polygonal area, how should I use it?

**Comment by p-lr** [comment]
You can achieve this by adding a custom view which is registered as a `ReferentialListerner`. See the doc [here](https://github.com/peterLaurence/MapView#-referentiallistener). If your polygon area needs to scale when the user zoom, you can set the scale of the canvas using the scale of the `ReferentialOwner` (your custom view).
Using a custom view, you can draw anything you want on the MapView, and position/scale/rotate it accordingly.
