### ISSUE TITLE
Possibility to zoom farther out?

### ISSUE THREAD

**Issue by devjta** [peterLaurence/MapView#42]
Hey!

Would it be possible, to support zooming out? Lets say, I dont have an infinite map, but its limited to a certain area and I want to see the whole area in a view.

But even with zoomLevel0, the space would be too small.

I can also change the code, if the option doesnt make sense for general purposes, but where should I try it?

So it doesnt need load any additional tile, but basically let the zoomlevel going into negative?

**Comment by p-lr** [comment]
Hi,

Is the default `MinimumScaleMode.FIT` (which limits the minimum scale to no less than what would be required to fit inside the container) not enough ?
If so, have you tried to set the minimum scale using the `setMinScale` api? (see [this example](https://github.com/p-lr/MapView/blob/master/demo/src/main/java/ovh/plrapps/mapview/demo/fragments/MapPathFragment.kt))
