### ISSUE TITLE
Issue when setting compileSdkVersion to 34

### ISSUE THREAD

**Issue by Heitem** [peterLaurence/MapView#43]
I get this error when I set the `compileSdkVersion` to 34:
`Class 'TileView' is not abstract and does not implement abstract base class member public abstract fun onFling(p0: MotionEvent?, p1: MotionEvent, p2: Float, p3: Float): Boolean defined in ovh.plrapps.mapview.MapView`

**Comment by p-lr** [comment]
Yes indeed, I need to publish a new version compatible with api 34. Will do asap.

**Comment by p-lr** [comment]
The version 3.1.7 is released
