### ISSUE TITLE
Error on zoom near of border

### ISSUE THREAD

**Issue by aluismarte** [peterLaurence/MapView#7]
Everithing work fantastic, but when i put a point near of a border, give a distortion when i do zoom in or zoom out

        val config =
            MapViewConfiguration(8, 24000, 22000, 256, tileStreamProvider)
                .setMaxScale(1.2f)
                .setWorkerCount(4)
                .setPadding(256)
                .setMagnifyingFactor(0)
                .setMinimumScaleMode(MinimumScaleMode.FILL)

mpMap.defineBounds(0.0, 120.0, 100.0, 0.0)

point on 71.09375, 91.78125 (near of a border)

Error on zoom out
![error-part-1](https://user-images.githubusercontent.com/2516303/75618267-241beb00-5b42-11ea-8790-445876ae4609.png)
![Error-part-3](https://user-images.githubusercontent.com/2516303/75618289-75c47580-5b42-11ea-9ae1-2a95adb69268.png)

zoom in and error show it
Real position of point
![error-part-2](https://user-images.githubusercontent.com/2516303/75618268-254d1800-5b42-11ea-9fb8-e0356a76f061.png)

**Comment by p-lr** [comment]
By default, the MapView positions markers so that the fix point is at the bottom-center of the marker.
I believe that in your case, you want the center of the marker to be at (50.0, 60.0). Then, you should add the marker using:

```
addMarker(marker, x, y, relativeAnchorLeft = -0.5f, relativeAnchorTop = -0.5f)
```

**Comment by aluismarte** [comment]
Yes!, thanks! is fix
